x-config:
  - &EXPRESS_BUILDER "095437649667.dkr.ecr.us-east-1.amazonaws.com/md-app-api-builder:0.0.1"
  - &CONTAINER_NAME "md-api"
  - &DEPLOYMENT_IMAGE "095437649667.dkr.ecr.us-east-1.amazonaws.com/md-app-api-dev:0.0.2"
  - &DEPLOYER_CONTAINER_NAME "md-express-deployer"

version: '3.7'

services:
  dev:
    container_name: dynamodb3
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodata2:/home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
volumes:
  dynamodata2: {}
